# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-RandomPerson
version:      0.4
version_from: lib/Data/RandomPerson.pm
installdirs:  site
requires:
    Date::Calc:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
